env = Environment(CPPPATH = ['../../', './googletest-release-1.10.0', './googletest-release-1.10.0/googletest/include'])

env.Program(['Test_intelhex.cpp', '../../intelhexclass.cpp'], LIBS=['gtest_main', 'gtest', 'pthread'], LIBPATH=['googletest-release-1.10.0/build/lib'])
